######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 27 10:46:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += switchwidget.h
SOURCES += switchwidget.cpp
